name: http_provider
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
    sdk: ">=2.17.0 <3.0.0"

dependencies:
    dartz: ^0.10.1
    dio: ^4.0.6
    flutter:
        sdk: flutter
    freezed_annotation: ^2.0.3

dev_dependencies:
    build_runner: ^2.1.11
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.1
    freezed: ^2.0.3+1
