name: comic_vine_api_service
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
    sdk: ">=2.17.1 <3.0.0"

dependencies:
    dartz: ^0.10.1
    flutter:
        sdk: flutter
    freezed_annotation: ^2.0.3
    http_provider:
        path: ../http_provider

dev_dependencies:
    build_runner: ^2.1.11
    flutter_lints: ^2.0.1
    flutter_test:
        sdk: flutter
    freezed: ^2.0.3+1
    json_serializable: ^6.2.0
