name: comic_vine_api_repository
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
    sdk: ">=2.17.1 <3.0.0"
    flutter: ">=1.17.0"

dependencies:
    dartz: ^0.10.1
    flutter:
        sdk: flutter
    freezed_annotation: ^2.0.3
    comic_vine_api_service:
      path: ../comic_vine_api_service
    intl: ^0.17.0

dev_dependencies:
    build_runner: ^2.1.11
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.1
    freezed: ^2.0.3+1